package GUI;

import NapakalakiGame.BadConsequence;

/**
 *
 * @author Andres Arco Lopez
 */
public class PendingBadConsequenceView extends javax.swing.JPanel {

    /**
     * Creates new form PendingBadConsequence
     */
    BadConsequence pendingBadConsequenceModel;
    public PendingBadConsequenceView() {
        initComponents();
    }
    
    public void setPendingBadConsequence(BadConsequence pBC){
        this.pendingBadConsequenceModel = pBC;
        
        if(this.pendingBadConsequenceModel instanceof NapakalakiGame.NumericBadConsequence){
            ocultos.setText(Integer.toString(this.pendingBadConsequenceModel.getNHiddenTreasures()));
            visibles.setText(Integer.toString(this.pendingBadConsequenceModel.getNVisibleTreasures()));
        }else if (this.pendingBadConsequenceModel instanceof NapakalakiGame.SpecificBadConsequence){
            ocultos.setText(this.pendingBadConsequenceModel.getSpecificHiddenTreasures().toString());
            visibles.setText(this.pendingBadConsequenceModel.getSpecificVisibleTreasures().toString());
            }else if(this.pendingBadConsequenceModel instanceof NapakalakiGame.DeathBadConsequence){
                ocultos.setText(Integer.toString(this.pendingBadConsequenceModel.getNHiddenTreasures()));
                visibles.setText(Integer.toString(this.pendingBadConsequenceModel.getNVisibleTreasures()));
                }else{   
                    noPending.setText("No hay mal rollo pendiente.");
                    ocultos.setText("-----");
                    visibles.setText("-----");
                    }    
        ocultos.setVisible(true);
        visibles.setVisible(true);
        noPending.setVisible(true);
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noPending = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ocultos = new javax.swing.JLabel();
        visibles = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Mal Rollo Pendiente"));

        jLabel1.setText("Ocultos:");

        jLabel2.setText("Visibles:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noPending, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(visibles, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ocultos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(noPending, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ocultos, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visibles, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel noPending;
    private javax.swing.JLabel ocultos;
    private javax.swing.JLabel visibles;
    // End of variables declaration//GEN-END:variables
}
